iterative/example-repos-dev

example-get-started/code/src/prepare.py

In https://github.com/iterative/example-get-started/blob/master/src/prepare.py, the error should specify data-file instead of just data, as data is a directory in the same tutorial
It will lead to clearer explanation, and is also in reference to iterative/dataset-registry#6

Changed error message from 'data' to 'data-file'

---

example-get-started/code/README.md
example-get-started/code/params.yaml
example-get-started/code/src/evaluate.py
example-get-started/code/src/featurization.py
example-get-started/code/src/prepare.py
example-get-started/code/src/train.py
example-get-started/deploy.sh
example-get-started/generate.sh

@jorgeorpinel a branch to play with 1.0 - it generates a project ready to use

update get-started to 1.0

---

example-get-started/code/README.md

The README.md assumes that the user which is just getting started with dvc, already has dvc installed.
By adding this note the user will know that it can install dvc if it is missing.

Update example-get-started readme

---

example-get-started/generate.sh

Adds remote experiments to example-get-started repo.
See https://github.com/iterative/dvc.org/pull/2259#discussion_r596120116.

push experiments to remote

---

example-get-started/generate.sh

Sorry, looks like the `dvc add` gets overwritten later by a `dvc import` later, so moved `--desc` to the later command to keep it in the final example repo.

Move desc to import

---

example-get-started/generate.sh

I can't test this on my laptop for some reason but should work to update timestamp, author, and email of commits. 
For github.com/iterative/example-get-started/ repository:
* Starts 15 * 100,000 seconds before now and puts 100.000 seconds between each tag
* Sets author/committer to "Olivaw Owlet"
* Sets email to `64868532+iterative-olivaw@users.noreply.github.com`

Modified to have delays between commits and custom author and email

---

example-get-started/code/.github/workflows/cml.yaml
example-get-started/deploy.sh
example-get-started/generate.sh

Uses:
It also runs on each commit which may be annoying (https://github.com/iterative/cml/issues/512).

initial CML workflow

---

get-started-experiments/generate.bash

Closes #68
`dvc exp show --all-tags` now shows the tag names

modified to create lightweight tags instead of annotated

---

example-dvc-experiments/generate.bash

This provides syntax-highlighting support for .dvc and dvc.lock files in the Github.
See #72 and #73.

example-dvc-experiments: cp .gitattributes

---

example-dvc-experiments/code/src/train.py
example-dvc-experiments/code/src/util.py
example-dvc-experiments/generate.bash

This fixes #86 
- It shows the following warning when pushing the generated repo. It may need further tweaks.

marks model.h5 as a cached output

---

example-dvc-experiments/generate.bash

Related to #98. Extract stage was producing too much output.

`example-dvc-experiments`: removed -v from tar in extract stage

---

example-get-started/code/.github/workflows/cml.yaml

In PRs we now compare metrics and plots with `main`, in the `main` itself we are comparing with `HEAD^1`
Closes https://github.com/iterative/example-repos-dev/issues/58 
Needs some testing, but for simplicity I'm postponing this until I can run everything end to end with all the changes I want to make: add a separate branch for the 4x data, add codespaces, change author names (I believe any human name and face is better than Olivaw)

get-started: compare with main or previous commit in the CML workflow

---

example-get-started/code/.github/workflows/cml.yaml

Use actions instead of containers
Use fetch-depth 2 to fix action running on master

get-started: fix CML workflow

---

example-get-started/generate.sh

`dvc exp` commands now support removing and pushing multiple experiments, so we don't need the previous `xargs` hacks.

simplify dvc exp push commands

---

example-get-started/code/params.yaml

Using a fractional value for `min_split` (see https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) reduces overfitting and scales better to different sample sizes.
train.min_split=2
train.min_split=0.01

get-started: use fractional min_split

---

example-get-started/code/.github/workflows/cml.yaml

The cli for cml has been updated, it's best if our examples use the new command structure.

Update use of cml cli

---

example-mlem-get-started/code/README.md
example-mlem-get-started/code/src/evaluate.py
example-mlem-get-started/code/src/train.py
example-mlem-get-started/generate.sh

Updating `example-mlem-get-started` to run with MLEM 0.3.0
TODO:
Can be finished after fixing this bug: https://github.com/iterative/mlem/issues/418

MLEM: release 0.3.0

---

example-dvc-experiments/code/requirements-macos.txt
example-dvc-experiments/code/requirements.txt

Seems like the requirements are a bit overly restrictive here and the pinned versions are no longer available. I think it's enough to have a lower bound (if there's a tensorflow 3.0, we can revisit).

example-dvc-experiments: remove upper bound on tensorflow

---

example-get-started/code/.github/workflows/cml.yaml

`dvc plots diff` target paths pointed to non-existent locations and caused `vl2svg` to fail.

example-get-started: fix plot paths

---

example-gto/code/mlem/.github/workflows/deploy-model-with-mlem.yml
example-gto/code/mlem/.mlem.yaml
example-gto/code/mlem/deploy/dev.mlem
example-gto/code/mlem/deploy/prod.mlem
example-gto/code/mlem/deploy/staging.mlem

Follow-up for #133 
Fixing CI and renaming apps due to `gto-example-mlem-app-prod` already taken.
I re-generated the example-gto repo again, everything looks fine https://github.com/iterative/example-gto/actions
Now for heroku apps we use names `mlem-dev`, `mlem-staging` and `mlem-prod`. All belong to Olivaw's account.
Feel free to merge if looks correct.

GTO: fix CI

---

example-get-started/deploy.sh
example-get-started/generate.sh

example-get-started: `dvc run` -> `dvc stage add`

---

example-get-started/code/README.md

Metric file path has recently changed + for whatever reason `logo=data-version-control` doesn't work anymore.

example-get-started: fix DVC badge

---

.devcontainer.json

Add `.devcontainer.json` config for Codespaces per https://github.com/iterative/example-repos-dev/pull/161#discussion_r1088142263
Related: https://github.com/iterative/saml-to repo to define [SAML.to](https://saml.to/) config to assume role automatically that has access to S3 (including `dvc-private` and `dvc-public`) buckets.
To debug (if something goes wrong) the SAML.to logic one can run:
```cli
$ assume-aws-role
```
Also make sure (ask GH admins) that SAML.to app has access to the https://github.com/iterative/saml-to repo.

Add devcontainer to run in Codespaces

---

example-get-started/generate.sh

Per https://github.com/iterative/example-repos-dev/pull/181#issuecomment-1416894583

example-get-started: add link to Studio wiki in instructions

---

example-get-started-experiments/code/notebooks/TrainSegModel.ipynb
example-get-started-experiments/code/params.yaml

Changed model arch to something that runs in reasonable time on cpu since I think it's not feasible for everyone trying it out to have access to gpu (or they may have some restricted access to one that they don't want to use to demo a new tool). Performance is not quite as strong but it's not a dramatic dropoff:

example-get-started-experiments: use cpu-friendly arch

---

example-gto/code/.github/workflows/gto-act-on-tags.yml
example-gto/code/mlem/.github/workflows/deploy-model-with-mlem.yml
example-gto/generate.sh

- the repo can be re-generated already, although CI will fail
- we need to update GTO action to v2 to make it work in CI
- test repo for Studio BE should have a monorepo. Given `example-gto`, one can ~generate monorepo with simply
```sh
$ cp -r * example-gto example-gto/subrepo
$ cd example-gto
```
Now you'll have a very simple monorepo 🙌🏻 
cc @jellebouwman and @amritghimire re https://github.com/iterative/studio/issues/5504 - I'm not sure `demo-bank-customer-churn` is a monorepo, so if you need one, we can do this ^

`example-gto`: remove `annotate` and move artifacts to `dvc.yaml`

---

example-get-started-experiments/code/.github/workflows/run-experiment.yml

- Use `on push` trigger
Using `pull_request` requires modifying the action/checkout step in order to properly set the git HEAD (which was causing the experiments to appear as detached in Studio)
on push has the same effect and we use the github actor to filter events
- Use `exp push` for sharing in workflow dispatch mode.
You can manually replicate from github UI the future Studio UI behavior

More CI workflow updates

---

example-get-started/code/.github/workflows/cml.yaml

Fixes https://github.com/iterative/example-repos-dev/issues/225
`json5` CLI replaces `Infinity` and other non-JSON.parse values with `null` which is "fine" with Vega.
Since we have PRs broken in the example repo https://github.com/iterative/example-get-started/actions/runs/5484365547/job/14852022942?pr=53 and I failed to demo it the last week.
It's a workaround for now. The best fix it work with Vega to fix their CLI - https://github.com/vega/vega-lite/issues/9026. I'm not sure it's a priority at the moment since we have quick workaround if needed, JS version of Vega seems to work fine, and I'm not sure for the long term future of Vega in the project (tbh we need to migrate I think to something else after all as soon as we have more time and resources).

fix(example-get-started): avoid inf and nans in prc plot output

---

example-get-started/generate.sh

As part of the https://github.com/iterative/studio-support/issues/89 . It add a way to use Azure private storage to generate a fixture like this: https://github.com/iterative/example-get-started-azure-private-fixture to then be used in the tests, or degug.

feat(example-get-started): add azure private remote

---

example-get-started/README.md

Minor update so that `gh create pr` doesn't fail and we don't accidentally leave stale PRs.

add instructions to close prs

---

.github/workflows/example-get-started-test.yaml

Step 1 in trying to setup some automation of this repo. This PR adds only an action to test that `example-get-started/generate.sh` runs successfully when changes to `example-get-started` are pushed. Next would be to make another action to do all the deployment steps when a PR is merged, and then we could add similar actions for `example-get-started-experiments`.

add gha to test example-get-started

---

.github/workflows/example-get-started-experiments-test.yaml

Similar to the recent action added to generate `example-get-started`, this does the same for `example-get-started-experiments`. It also uses the cml runner to launch a self-hosted instance for training.
This requires a `PERSONAL_ACCESS_TOKEN` be added to the repo. @daavoo @shcheklein How did we set up the token for `example-get-started-experiments`? Can/should we use the same here?

initial gha to test example-get-started-experiments

---

example-get-started/generate.sh

I [recently](https://github.com/iterative/example-repos-dev/pull/238) added an extra commit to convert from auto-dvclive configuration to custom plots configuration. However, I missed that since we never call `Live. end()` or `Live.make_dvcyaml()` in this repo, we never generate the auto config. In this PR, I revert back to having a single eval commit.

example-get-started: remove unneeded eval customization stage

---

example-get-started/code/.github/workflows/cml.yaml
example-get-started/code/README.md
example-get-started/code/src/evaluate.py

Fixes (bumped today into this):
It's better to cache images I think. It creates a stronger example on how things could be managed (I got a question today if images could be cached or not). It's better since we cover a bit more advanced scenario + probably ppl will use it this way.

fix(example-get-started): cache images, fix reports action

---

example-get-started/README.md
example-get-started/code/.github/workflows/cml.yaml
example-get-started/code/README.md
example-get-started/code/src/evaluate.py
example-get-started/generate.sh

Fixes #249 
Simplify eval stage by tracking the whole eval directory with metrics, plots, etc.
Probably next step should be to get rid of the custom name, use log_artifact for models.
Tested it here https://github.com/shcheklein/example-get-started

fix(example-get-started): track the whole eval dir for simplicity

---

.github/workflows/example-get-started-deploy.yaml
.github/workflows/example-get-started-test.yaml
README.md
example-get-started/README.md

Adds a workflow to auto deploy on any push to master. Unfortunately, according to https://github.com/orgs/community/discussions/25746, it looks like I can't try it until it gets merged to master first, so I'm opening the PR to merge and expecting to follow up after I can try it and debug.
After I get it working for this repo, I'll plan to do the same for example-get-started-experiments.

add gha to deploy example-get-started

---

example-get-started-experiments/code/.github/workflows/deploy-model.yml
example-get-started-experiments/code/.github/workflows/dvc-studio.yml

Changes for https://github.com/iterative/studio/pull/7773 + some fixes

Add parent-sha input

---

.github/workflows/example-get-started-deploy.yaml

example-get-started code wasn't being deployed. See https://github.com/iterative/dvc.org/issues/4901.

fix prod flag

---

.github/workflows/example-get-started-deploy.yaml
example-get-started/deploy.sh

Per https://github.com/iterative/example-repos-dev/actions/runs/6433803421/job/17471645914#step:6:931, this was causing the deployment workflow to fail. I think it shouldn't be needed since the acl is already set for that path. I was able to deploy without it and download the updated code.

Drop acl from s3 upload

---

example-get-started-experiments/generate.sh

Fixes missing training metrics. Before this PR, we are only capturing `results` as an output of the evaluate stage, but `results/train` is actually generated during the train stage, and then is getting deleted by dvc during the evaluate stage, dropping the training metrics. This PR fixes it by granularly tracking `results/train` as an output of the train stage and `results/evaluate` as an output of the `evaluate` stage.

experiments: split dvclive outputs by train/eval

---

example-get-started-experiments/code/sagemaker/deploy_model.py

Closes #265. Tested in https://github.com/iterative/example-get-started-experiments/actions/runs/6460826300/job/17539284730.

Deletes model endpoint to avoid errors deploying to existing endpoint

---

example-get-started/README.md
example-get-started/generate.sh

Adds GDrive remote option to test Studio. I've updated the fixture here: https://github.com/iterative/example-get-started-gdrive-private-fixture/

feat(example-get-started): add an option for GDrive remote

---

example-get-started-experiments/code/.github/workflows/deploy-model-sagemaker.yml
example-get-started-experiments/code/.github/workflows/dvc-studio.yml
example-get-started-experiments/code/requirements.txt

Attempts to fix:
- https://github.com/iterative/example-get-started-experiments/actions/runs/6896818532
- https://github.com/iterative/example-get-started-experiments/actions/runs/6896818531

updates vars and secrets in ci

---

example-get-started-experiments/code/data/pool_data.dvc

Somehow we never updated the pool data to the 3.0 cache (the stack overflow data in the other repo is already updated).

experiments: use 3.0 cache for pool data

---

example-get-started-experiments/code/notebooks/TrainSegModel.ipynb
example-get-started-experiments/generate.sh

This PR makes the notebook and pipeline code more similar by modifying the notebook code to use the same paths and otherwise reusing the code from the pipeline. The changes from the notebook to the pipeline were probably more realistic than making them both so similar, but it makes the repo harder to understand and maintain.

experiments: make notebook more like the pipeline

---

example-get-started-experiments/generate.sh

Fixes https://github.com/iterative/studio/issues/8951.
It looks like this must be a bug in dulwich or scmrepo. When `GIT_COMMITTER_DATE` is set, it causes `GIT_COMMITTER_NAME` to be ignored. This is not the case for CLI Git, and the dates and formats appear valid. I don't see a need for this var anywhere (`GIT_AUTHOR_DATE` seems to be enough for the commits), so it looks easiest to drop this.

drop GIT_COMMITTER_DATE
