- create.sh
To pair up with recent changes in the [docs repo](https://github.com/iterative/dvc.org).
Also, I may need this fork in the near future to update the get started section of the docs...
> term: review usage of "source"

- example-get-started/code/README.md
- example-get-started/code/params.yaml
- example-get-started/code/src/evaluate.py
- example-get-started/code/src/featurization.py
- example-get-started/code/src/requirements.txt
- example-get-started/code/src/train.py
- example-get-started/generate.sh
Updates to match https://github.com/iterative/dvc.org/pull/2195. Also fixes #20.
`deploy.sh` and `generate.sh` scripts ran with no errors and expected outputs.
> Adds experiments for 2.0

- example-get-started/code/src/evaluate.py
> indent json

- example-get-started/code/src/featurization.py
> Remove pickle protocol for backwards compatibility

- example-get-started/code/README.md
Reference https://github.com/iterative/example-get-started/pull/6
> Correct Typos in Readme

- .pre-commit-config.yaml
- example-get-started/code/src/evaluate.py
- example-get-started/code/src/featurization.py
- example-get-started/code/src/prepare.py
- example-get-started/code/src/train.py
- example-get-started/deploy.sh
- example-get-started/generate.sh
- simplify `generate.sh` (follow-up to #36)
- simplified diff: https://github.com/iterative/example-repos-dev/pull/41/files?file-filters%5B%5D=.sh&w=1
- add pre-commit linting
- run linting with @iterative-olivaw
> Simplification & linting

- example-get-started/generate.sh
> fix #51 to make sed work across mac/linux

- get-started-experiments/code-experiments/README.md
- get-started-experiments/generate.bash
There are some changes required for the selected option of Experiments Trail in iterative/dvc.org#2574 
This one fixes these issues and closes #61
> get-started-experiments: Fix minor issues to conform the GS:Experiments Trail

- get-started-experiments/generate.bash
> adds /data/images/ to .gitignore

- get-started-experiments/generate.bash
> added model.h5 to .gitignore

- get-started-experiments/generate.bash
Closes #64 
Also fixes the parameter names in the script
> Added deletion of remote experiments

- README.md
> Add naming convention for the new repositories to the Readme

- example-dvc-experiments/.gitattributes
- example-dvc-experiments/generate.bash
- example-get-started/.gitattributes
- example-get-started/generate.sh
> Add .gitattributes for syntax-highlighting .dvc and dvc.lock files

- example-dvc-experiments/code/src/train.py
This removes 4 lines from `train.py`.
> Removed commented code from train.py (Related #85)

- example-get-started/code/.github/workflows/cml.yaml
> CML workflow tidy

- example-get-started/generate.sh
> Use main branch in the example-get-started

- example-get-started/generate.sh
Fixes #50 
+ Use real author names, it looks better in Studio
Still need to generate the PR + launch action on the last commit. `gh` app or something like that is needed.
> get-started: codify 4x data branch

- example-get-started/generate.sh
Per https://github.com/iterative/example-repos-dev/pull/109#discussion_r855322114 - we don't need gitpython anymore here
> get-started: remove gitpython, add a comment

- example-mlem-get-started/code/src/train.py
generator change for https://github.com/iterative/mlem/pull/370
> Remove `description` from MLEM example

- README.md
- example-get-started/deploy.sh
- example-get-started/generate.sh
@shcheklein Here's a proposed attempt to address #129. Let me know what you think.
> example-get-started: make dev/prod generate.sh and source deploy.sh

- example-gto/code/.github/workflows/gto-act-on-tags.yml
- example-gto/generate.sh
> Make `example-gto` work with `gto==0.2.1`

- example-get-started/code/src/evaluate.py
- example-get-started/code/src/requirements.txt
- example-get-started/generate.sh
> example-get-started: dvclive 1.0 updates

- example-get-started/code/.github/workflows/cml.yaml
See https://github.com/iterative/example-get-started/pull/33 for context
> example-get-started: add `git fetch` to workflow

- example-gto/code/.github/workflows/gto-act-on-tags.yml
- example-gto/code/README.md
- example-gto/code/mlem/.github/workflows/deploy-model-with-mlem.yml
implements https://github.com/iterative/gto/issues/303
> GTO: update README

- example-get-started/generate.sh
See https://github.com/iterative/dvc.org/pull/4207#discussion_r1068268762. tldr: This updates better matches the text in https://dvc.org/doc/start/data-management/metrics-parameters-plots#visualizing-plots.
> example-get-started: update plots ordering

- example-get-started/generate.sh
Use `simple` template for ROC and PRC curves
> example-get-started: update plot templates

- example-get-started/code/src/evaluate.py
- example-get-started/code/src/requirements.txt
- example-get-started/generate.sh
Updates requirements and adds `Live(dvcyaml=False)`.
> Dvclive 2.0 updates

- example-get-started-experiments/code/requirements.txt
- example-get-started-experiments/code/src/evaluate.py
- example-get-started-experiments/code/src/train.py
- example-get-started-experiments/generate.sh
Closes https://github.com/iterative/example-repos-dev/issues/183
> Experiments followups

- example-get-started-experiments/code/.devcontainer.json
Moved from https://github.com/iterative/example-get-started-experiments/pull/91
> Remove DVC feature from devcontainer

- example-get-started-experiments/code/requirements.txt
- example-get-started-experiments/code/src/evaluate.py
- example-get-started-experiments/code/src/train.py
- example-get-started-experiments/generate.sh
Fixes #190. Unfortunately I haven't been able to regenerate the repo since I don't have GPU access, so I'm leaving this PR in draft mode.
> experiments: use Live(dvcyaml=True)

- example-get-started/code/src/evaluate.py
- example-get-started/code/src/featurization.py
- example-get-started/code/src/prepare.py
- example-get-started/code/src/train.py
The reason for the PR is to make the source code clearer for the `example-get-started` while keeping it as simple as possible. The actual code was left unchanged.
Here are my changes for a more understandable starter source code:
- Formatted files using black code style
- Update the Python source code to make it clearer
- Modularise code into functions
- Document functions
> example-get-started: Update src code

- example-get-started-experiments/README.md
- example-get-started-experiments/code/README.md
part of https://github.com/iterative/example-repos-dev/issues/203
> Update README.md to include adding a model to Model Registry

- example-get-started-experiments/code/.github/workflows/run-experiment.yml
- example-get-started-experiments/code/.github/workflows/runs-studio-experiment.yml
This is the current deployed version in https://github.com/iterative/example-get-started-experiments
> Bring back commit-based CI

- .devcontainer.json
- example-get-started-experiments/README.md
- example-get-started-experiments/code/notebooks/TrainSegModel.ipynb
- example-get-started-experiments/code/src/train.py
- example-get-started-experiments/generate.sh
- example-get-started/code/.github/workflows/cml.yaml
- example-get-started/code/src/featurization.py
- example-get-started/code/src/train.py
- example-get-started/generate.sh
- example-get-started/generate_data.py
> Add model and register versions

- example-get-started-experiments/README.md
https://github.com/iterative/example-get-started-fixture
https://github.com/iterative/example-get-started-experiments-fixture
> Update name of fixture repos 

- example-get-started-experiments/README.md
- example-get-started/README.md
- example-get-started/generate.sh
Addresses partially https://github.com/iterative/studio/issues/6559 .
Add a way to generate repos similar to these ones:
> feat(example-get-started): config to generate nested repos

- example-get-started/generate.sh
Minor follow up fix after #214 .
> fix(example-get-started): update default values

- .devcontainer.json
- example-get-started-experiments/README.md
- example-get-started-experiments/code/.github/workflows/dvc-studio.yml
Per https://github.com/iterative/studio/pull/6755
> Rename run-experiment to dvc-studio. Add cml runner inputs.

- .github/workflows/example-get-started-experiments-test.yaml
Fixes after testing the example-get-started-experiments CI workflow
> Gha experiments debug

- .github/workflows/example-get-started-experiments-test.yaml
- .github/workflows/example-get-started-test.yaml
- example-get-started-experiments/code/.github/workflows/deploy-model.yml
- example-get-started-experiments/code/.github/workflows/dvc-studio.yml
Cleaner, and simpler for @iterative/platform to maintain.
> Use organization-wide variable for OIDC AWS sandbox role

- example-get-started-experiments/code/.github/workflows/deploy-model.yml
Continuation of #252 & https://github.com/iterative/example-repos-dev/pull/233#discussion_r1294012207
> Use AWS_SAGEMAKER_ROLE

- .github/workflows/example-get-started-deploy.yaml
- .github/workflows/example-get-started-experiments-deploy.yaml
- .github/workflows/example-get-started-test.yaml
- README.md
- example-get-started/README.md
Debugs #256 to make it work and adds a similar workflow for example-get-started-experiments
> GitHub Actions: Deploy Repos

- example-get-started-experiments/code/requirements.txt
Per https://github.com/iterative/dvclive/pull/715/files
> experiments: bump requirements

- .github/workflows/example-get-started-deploy.yaml
- .github/workflows/example-get-started-experiments-deploy.yaml
Tested that this one succeeds: https://github.com/iterative/example-repos-dev/actions/runs/6326382609
> Fix command to activate venv

- .github/workflows/example-get-started-experiments-deploy.yaml
- .github/workflows/example-get-started-experiments-test.yaml
- example-get-started-experiments/code/.github/workflows/dvc-studio.yml
- example-get-started/code/.github/workflows/cml.yaml
> upgrade to setup-cml@v2

- example-get-started-experiments/code/requirements.txt
- example-get-started-experiments/code/sagemaker/deploy_model.py
Per https://github.com/iterative/example-repos-dev/pull/233#issuecomment-1682457335
> WIP: Single endpoint per stage
